# Trabajo integrador - Parte 1
## Python y Numpy

**Nombre**:

In [2]:
import numpy as np
import pandas as pd

## Ejercicio 1

Dada una matriz en formato *numpy array*, donde cada fila de la matriz representa un vector matemático, se requiere computar las normas $l_0$, $l_1$, $l_2$, $l_{\infty}$, según la siguientes definiciones:

\begin{equation}
    ||\mathbf{x}||^{p} = \bigg(\sum_{j=1}^{n}{|x_i|^p}\bigg)^{\frac{1}{p}}
\end{equation}

con los casos especiales para $p=0$ y $p=\infty$ siendo:

\begin{equation}
    \begin{array}{rcl}
        ||\mathbf{x}||_0 & = & \bigg(\sum_{j=1 \wedge x_j != 0}{|x_i|}\bigg)\\
        ||\mathbf{x}||_{\infty} & = & \max_{i}{|x_i|}\\
    \end{array}
\end{equation}

In [3]:
def norm(arr,p):
    if p==0:
        return np.count_nonzero(arr,axis=-1)
    elif p==float('inf'):
        return np.max(np.abs(arr),axis=-1)
    else:
        return (np.sum(np.power(np.abs(arr),p),axis=-1))**(1/p)

test_array=np.array([[1,2],[3,4],[5,6]])
print(norm(test_array,0))
print(norm(test_array,10))
print(norm(test_array,float('inf')))

[2 2 2]
[2.00019523 4.02197415 6.09050607]
[2 4 6]


## Ejercicio 2

En clasificación contamos con dos arreglos, la “verdad” y la “predicción”. Cada elemento de los arreglos pueden tomar dos valores, “True” (representado por 1) y “False” (representado por 0). Entonces podemos definir 4 variables:

* True Positive (TP): El valor verdadero es 1 y el valor predicho es 1
* True Negative (TN): El valor verdadero es 0 y el valor predicho es 0
* False Positive (FP): El valor verdadero es 0 y el valor predicho es 1
* False Negative (FN): El valor verdadero es 1 y el valor predicho es 0

A partir de esto definimos:

* Precision = TP / (TP + FP)
* Recall = TP / (TP + FN)
* Accuracy = (TP + TN) / (TP + TN + FP + FN)
 
Calcular las 3 métricas con Numpy y operaciones vectorizadas.

In [12]:
truth = np.array([1,1,0,1,1,1,0,0,0,1])
prediction = np.array([1,1,1,1,0,0,1,1,0,0])

FN = np.count_nonzero(truth > prediction)
FP = np.count_nonzero(prediction > truth)
TP = np.count_nonzero(np.logical_and(prediction,truth))
TN = np.count_nonzero(np.logical_not(np.logical_or(prediction,truth)))

precision = TP/(TP+FP)
recall = TP / (TP + FN)
accuracy = (TP + TN)/(TP + TN + FP + FN)

pd.DataFrame(data={'Precision':precision,'Recall':recall,'Accuracy':accuracy},index=[0])


Precision  Recall  Accuracy
0        0.5     0.5       0.4

## Ejercicio 3

Crear una función que separe los datos en train-validation-test. Debe recibir de parametros:

- X: Array o Dataframe que contiene los datos de entrada del sistema.
- y: Array o Dataframe que contiene la(s) variable(s) target del problema.
- train_percentage: _float_ el porcentaje de training.
- test_percentage: _float_ el porcentaje de testing.
- val_percentage: _float_ el porcentaje de validación.
- shuffle: _bool_ determina si el split debe hacerse de manera random o no.

Hints: 

* Usar Indexing y slicing
* Usar np.random.[...]

In [49]:
def split(X_input,
          Y_input,
          train_size=0.7,
          val_size=0.15,
          test_size=0.15,
          random_state=42,
          shuffle=True):
    
    if X_input.shape[0] != Y_input.shape[0]: return TypeError
    rnd = np.random.default_rng(random_state)
    mixed = np.append(X_input,Y_input,axis=1)
    print(rnd.random(1))
    return rnd.permutation(mixed)

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2,3,4],[3,4,5,6]])
print(split(x,y,random_state=12))

[0.25082446]
[[4 5 6 3 4 5 6]
 [1 2 3 1 2 3 4]]
